version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/smriti-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/smriti-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
